let books = [
  {
  id: 1,
  title: "Le Seigneur des Anneaux",
  category_id: 9,
  author_id: 1,
  publisher_id: 1,
  comment_id: 1,
  assessment_id: 1,
  customer_id: 1,
  number_of_pages: 500,
  year_of_publication: 1954,
  average_ratings: null,
  cover_image: "https://example.com/book1-cover.jpg",
  extract_pdf: "https://example.com/book1-extract.pdf",
  summary: "Un récit épique dans un monde fantastique...",
},
{
  id: 2,
  title: "Fondation",
  category_id: 2,
  author_id: 2,
  publisher_id: 2,
  comment_id: 2,
  assessment_id: 2,
  customer_id: 2,
  number_of_pages: 300,
  year_of_publication: 1951,
  average_ratings: null,
  cover_image: "https://example.com/book2-cover.jpg",
  extract_pdf: "https://example.com/book2-extract.pdf",
  summary: "L'histoire de la Fondation à travers les âges...",
},
{
  id: 3,
  title: "Sherlock Holmes",
  category_id: 3,
  author_id: 3,
  publisher_id: 3,
  comment_id: 3,
  assessment_id: 3,
  customer_id: 3,
  number_of_pages: 350,
  year_of_publication: 1892,
  average_ratings: null,
  cover_image: "https://example.com/book3-cover.jpg",
  extract_pdf: "https://example.com/book3-extract.pdf",
  summary: "Les enquêtes du célèbre détective...",
},
{
  id: 4,
  title: "Orgueil et Préjugés",
  category_id: 4,
  author_id: 4,
  publisher_id: 4,
  comment_id: 4,
  assessment_id: 4,
  customer_id: 4,
  number_of_pages: 400,
  year_of_publication: 1813,
  average_ratings: null,
  cover_image: "https://example.com/book4-cover.jpg",
  extract_pdf: "https://example.com/book4-extract.pdf",
  summary: "Une histoire d'amour classique...",
},
{
  id: 5,
  title: "The Da Vinci Code",
  category_id: 5,
  author_id: 5,
  publisher_id: 5,
  comment_id: 5,
  assessment_id: 5,
  customer_id: 5,
  number_of_pages: 450,
  year_of_publication: 2003,
  average_ratings: null,
  cover_image: "https://example.com/book5-cover.jpg",
  extract_pdf: "https://example.com/book5-extract.pdf",
  summary: "Un thriller ésotérique captivant...",
},
{
  id: 6,
  title: "Les Misérables",
  category_id: 6,
  author_id: 6,
  publisher_id: 1,
  comment_id: 6,
  assessment_id: 6,
  customer_id: 6,
  number_of_pages: 550,
  year_of_publication: 1862,
  average_ratings: null,
  cover_image: "https://example.com/book6-cover.jpg",
  extract_pdf: "https://example.com/book6-extract.pdf",
  summary: "L'épopée de Jean Valjean...",
},
{
  id: 7,
  title: "Sapiens",
  category_id: 7,
  author_id: 7,
  publisher_id: 2,
  comment_id: 7,
  assessment_id: 7,
  customer_id: 7,
  number_of_pages: 600,
  year_of_publication: 2011,
  average_ratings: null,
  cover_image: "https://example.com/book7-cover.jpg",
  extract_pdf: "https://example.com/book7-extract.pdf",
  summary: "Une brève histoire de l'humanité...",
},
{
  id: 8,
  title: "Steve Jobs",
  category_id: 8,
  author_id: 8,
  publisher_id: 3,
  comment_id: 8,
  assessment_id: 8,
  customer_id: 8,
  number_of_pages: 650,
  year_of_publication: 2011,
  average_ratings: null,
  cover_image: "https://example.com/book8-cover.jpg",
  extract_pdf: "https://example.com/book8-extract.pdf",
  summary: "La biographie du co-fondateur d'Apple...",
},
{
  id: 9,
  title: "Frankenstein",
  category_id: 9,
  author_id: 9,
  publisher_id: 4,
  comment_id: null,
  assessment_id: null,
  customer_id: 9,
  number_of_pages: 700,
  year_of_publication: 1818,
  average_ratings: null,
  cover_image: "https://example.com/book9-cover.jpg",
  extract_pdf: "https://example.com/book9-extract.pdf",
  summary: "L'histoire du docteur Frankenstein et de sa créature...",
},
{
  id: 10,
  title: "Cendrillon",
  category_id: 11,
  author_id: 10,
  publisher_id: 5,
  comment_id: null,
  assessment_id: null,
  customer_id: 10,
  number_of_pages: 250,
  year_of_publication: 2000,
  average_ratings: null,
  cover_image: "https://example.com/book10-cover.jpg",
  extract_pdf: "https://example.com/book10-extract.pdf",
  summary: "Une aventure mystérieuse...",
},
{
  id: 11,
  title: "Dune",
  category_id: 2,
  author_id: 2,
  publisher_id: 2,
  comment_id: null,
  assessment_id: null,
  customer_id: 1,
  number_of_pages: 800,
  year_of_publication: 1965,
  average_ratings: null,
  cover_image: "https://example.com/book11-cover.jpg",
  extract_pdf: "https://example.com/book11-extract.pdf",
  summary: "Une saga de science-fiction dans un univers désertique...",
},
{
  id: 12,
  title: "Moby Dick",
  category_id: 6,
  author_id: 6,
  publisher_id: 1,
  comment_id: null,
  assessment_id: null,
  customer_id: 2,
  number_of_pages: 750,
  year_of_publication: 1851,
  average_ratings: null,
  cover_image: "https://example.com/book12-cover.jpg",
  extract_pdf: "https://example.com/book12-extract.pdf",
  summary: "La quête obsessionnelle du capitaine Achab...",
},
{
  id: 13,
  title: "1984",
  category_id: 2,
  author_id: 2,
  publisher_id: 2,
  comment_id: null,
  assessment_id: null,
  customer_id: 3,
  number_of_pages: 300,
  year_of_publication: 1949,
  average_ratings: null,
  cover_image: "https://example.com/book13-cover.jpg",
  extract_pdf: "https://example.com/book13-extract.pdf",
  summary: "Une dystopie classique sur la surveillance et la manipulation...",
},
{
  id: 14,
  title: "Crime et Châtiment",
  category_id: 3,
  author_id: 3,
  publisher_id: 3,
  comment_id: null,
  assessment_id: null,
  customer_id: 4,
  number_of_pages: 450,
  year_of_publication: 1866,
  average_ratings: null,
  cover_image: "https://example.com/book14-cover.jpg",
  extract_pdf: "https://example.com/book14-extract.pdf",
  summary: "Les tourments psychologiques d'un criminel...",
},
{
  id: 15,
  title: "Guerre et Paix",
  category_id: 6,
  author_id: 6,
  publisher_id: 1,
  comment_id: null,
  assessment_id: null,
  customer_id: 5,
  number_of_pages: 1200,
  year_of_publication: 1869,
  average_ratings: null,
  cover_image: "https://example.com/book15-cover.jpg",
  extract_pdf: "https://example.com/book15-extract.pdf",
  summary: "Une fresque épique de la Russie du XIXe siècle...",
},
{
  id: 16,
  title: "L'Étranger",
  category_id: 3,
  author_id: 3,
  publisher_id: 3,
  comment_id: null,
  assessment_id: null,
  customer_id: 6,
  number_of_pages: 150,
  year_of_publication: 1942,
  average_ratings: null,
  cover_image: "https://example.com/book16-cover.jpg",
  extract_pdf: "https://example.com/book16-extract.pdf",
  summary: "L'histoire de Meursault, indifférent à sa propre existence...",
},
{
  id: 17,
  title: "Anna Karénine",
  category_id: 6,
  author_id: 6,
  publisher_id: 1,
  comment_id: null,
  assessment_id: null,
  customer_id: 7,
  number_of_pages: 800,
  year_of_publication: 1877,
  average_ratings: null,
  cover_image: "https://example.com/book17-cover.jpg",
  extract_pdf: "https://example.com/book17-extract.pdf",
  summary: "L'histoire tragique de la passion d'Anna...",
},
{
  id: 18,
  title: "Brave New World",
  category_id: 2,
  author_id: 2,
  publisher_id: 2,
  comment_id: null,
  assessment_id: null,
  customer_id: 8,
  number_of_pages: 350,
  year_of_publication: 1932,
  average_ratings: null,
  cover_image: "https://example.com/book18-cover.jpg",
  extract_pdf: "https://example.com/book18-extract.pdf",
  summary: "Une vision dystopique d'une société future...",
},
{
  id: 19,
  title: "Les Trois Mousquetaires",
  category_id: 10,
  author_id: 10,
  publisher_id: 5,
  comment_id: null,
  assessment_id: null,
  customer_id: 9,
  number_of_pages: 600,
  year_of_publication: 1844,
  average_ratings: null,
  cover_image: "https://example.com/book19-cover.jpg",
  extract_pdf: "https://example.com/book19-extract.pdf",
  summary: "Les aventures de d'Artagnan et des trois mousquetaires...",
},
{
  id: 20,
  title: "Le Petit Prince",
  category_id: 11,
  author_id: 5,
  publisher_id: 1,
  comment_id: null,
  assessment_id: null,
  customer_id: 10,
  number_of_pages: 100,
  year_of_publication: 1943,
  average_ratings: null,
  cover_image: "https://example.com/book20-cover.jpg",
  extract_pdf: "https://example.com/book20-extract.pdf",
  summary: "Les réflexions poétiques d'un petit prince venu d'une autre planète...",
},
{
  id: 21,
  title: "Le Seigneur des Anneaux",
  category_id: 1,
  author_id: 1,
  publisher_id: 1,
  comment_id: null,
  assessment_id: null,
  customer_id: 1,
  number_of_pages: 1200,
  year_of_publication: 1954,
  average_ratings: null,
  cover_image: "https://example.com/book21-cover.jpg",
  extract_pdf: "https://example.com/book21-extract.pdf",
  summary: "La quête de l'anneau unique pour sauver la Terre du Milieu...",
},
{
  id: 22,
  title: "Le Comte de Monte-Cristo",
  category_id: 10,
  author_id: 10,
  publisher_id: 5,
  comment_id: null,
  assessment_id: null,
  customer_id: 2,
  number_of_pages: 900,
  year_of_publication: 1844,
  average_ratings: null,
  cover_image: "https://example.com/book22-cover.jpg",
  extract_pdf: "https://example.com/book22-extract.pdf",
  summary: "La vengeance du jeune Edmond Dantès devenu le Comte de Monte-Cristo...",
},
{
  id: 23,
  title: "Le Rouge et le Noir",
  category_id: 3,
  author_id: 3,
  publisher_id: 3,
  comment_id: null,
  assessment_id: null,
  customer_id: 3,
  number_of_pages: 500,
  year_of_publication: 1830,
  average_ratings: null,
  cover_image: "https://example.com/book23-cover.jpg",
  extract_pdf: "https://example.com/book23-extract.pdf",
  summary: "Les ambitions et les passions de Julien Sorel...",
},
{
  id: 24,
  title: "Les Misérables",
  category_id: 10,
  author_id: 10,
  publisher_id: 5,
  comment_id: null,
  assessment_id: null,
  customer_id: 4,
  number_of_pages: 1463,
  year_of_publication: 1862,
  average_ratings: null,
  cover_image: "https://example.com/book24-cover.jpg",
  extract_pdf: "https://example.com/book24-extract.pdf",
  summary: "Les vies entrelacées de plusieurs personnages au cours des décennies...",
},
{
  id: 25,
  title: "L'Odyssée",
  category_id: 10,
  author_id: 10,
  publisher_id: 5,
  comment_id: null,
  assessment_id: null,
  customer_id: 5,
  number_of_pages: 384,
  year_of_publication: 1865,
  average_ratings: null,
  cover_image: "https://example.com/book25-cover.jpg",
  extract_pdf: "https://example.com/book25-extract.pdf",
  summary: "Le voyage épique d'Ulysse pour retourner chez lui après la guerre de Troie...",
},
{
  id: 26,
  title: "Orgueil et Préjugés",
  category_id: 4,
  author_id: 4,
  publisher_id: 4,
  comment_id: null,
  assessment_id: null,
  customer_id: 6,
  number_of_pages: 432,
  year_of_publication: 1813,
  average_ratings: null,
  cover_image: "https://example.com/book26-cover.jpg",
  extract_pdf: "https://example.com/book26-extract.pdf",
  summary: "L'amour complexe entre Elizabeth Bennet et Mr. Darcy...",
},
{
  id: 27,
  title: "Les Fleurs du Mal",
  category_id: 12,
  author_id: 2,
  publisher_id: 2,
  comment_id: null,
  assessment_id: null,
  customer_id: 7,
  number_of_pages: 128,
  year_of_publication: 1857,
  average_ratings: null,
  cover_image: "https://example.com/book27-cover.jpg",
  extract_pdf: "https://example.com/book27-extract.pdf",
  summary: "La poésie symboliste et controversée de Charles Baudelaire...",
},
{
  id: 28,
  title: "Le Nom de la Rose",
  category_id: 3,
  author_id: 3,
  publisher_id: 3,
  comment_id: null,
  assessment_id: null,
  customer_id: 8,
  number_of_pages: 536,
  year_of_publication: 1980,
  average_ratings: null,
  cover_image: "https://example.com/book28-cover.jpg",
  extract_pdf: "https://example.com/book28-extract.pdf",
  summary: "Un thriller médiéval mystérieux et intellectuel...",
},
{
  id: 29,
  title: "Le Château",
  category_id: 6,
  author_id: 6,
  publisher_id: 1,
  comment_id: null,
  assessment_id: null,
  customer_id: 9,
  number_of_pages: 352,
  year_of_publication: 1926,
  average_ratings: null,
  cover_image: "https://example.com/book29-cover.jpg",
  extract_pdf: "https://example.com/book29-extract.pdf",
  summary: "Une exploration kafkaïenne du pouvoir et de la bureaucratie...",
},
{
  id: 30,
  title: "Sapiens: Une brève histoire de l'humanité",
  category_id: 7,
  author_id: 7,
  publisher_id: 2,
  comment_id: null,
  assessment_id: null,
  customer_id: 10,
  number_of_pages: 464,
  year_of_publication: 2011,
  average_ratings: null,
  cover_image: "https://example.com/book30-cover.jpg",
  extract_pdf: "https://example.com/book30-extract.pdf",
  summary: "Un regard sur l'évolution de l'humanité depuis les premiers Homo sapiens...",
},
{
  id: 31,
  title: "Crime et Châtiment",
  category_id: 5,
  author_id: 5,
  publisher_id: 5,
  comment_id: null,
  assessment_id: null,
  customer_id: 1,
  number_of_pages: 551,
  year_of_publication: 1866,
  average_ratings: null,
  cover_image: "https://example.com/book31-cover.jpg",
  extract_pdf: "https://example.com/book31-extract.pdf",
  summary: "L'exploration psychologique du meurtrier Raskolnikov...",
},
{
  id: 32,
  title: "1984",
  category_id: 2,
  author_id: 2,
  publisher_id: 2,
  comment_id: null,
  assessment_id: null,
  customer_id: 2,
  number_of_pages: 328,
  year_of_publication: 1949,
  average_ratings: null,
  cover_image: "https://example.com/book32-cover.jpg",
  extract_pdf: "https://example.com/book32-extract.pdf",
  summary: "La dystopie classique d'un monde sous surveillance constante...",
},
{
  id: 33,
  title: "Anna Karénine",
  category_id: 4,
  author_id: 4,
  publisher_id: 4,
  comment_id: null,
  assessment_id: null,
  customer_id: 3,
  number_of_pages: 864,
  year_of_publication: 1877,
  average_ratings: null,
  cover_image: "https://example.com/book33-cover.jpg",
  extract_pdf: "https://example.com/book33-extract.pdf",
  summary: "L'histoire tragique de l'adultère d'Anna Karénine...",
},
{
  id: 34,
  title: "Le Parrain",
  category_id: 5,
  author_id: 5,
  publisher_id: 5,
  comment_id: null,
  assessment_id: null,
  customer_id: 4,
  number_of_pages: 448,
  year_of_publication: 1969,
  average_ratings: null,
  cover_image: "https://example.com/book34-cover.jpg",
  extract_pdf: "https://example.com/book34-extract.pdf",
  summary: "La montée au pouvoir de la famille mafieuse Corleone...",
},
{
  id: 35,
  title: "Le Portrait de Dorian Gray",
  category_id: 1,
  author_id: 1,
  publisher_id: 1,
  comment_id: null,
  assessment_id: null,
  customer_id: 5,
  number_of_pages: 254,
  year_of_publication: 1890,
  average_ratings: null,
  cover_image: "https://example.com/book35-cover.jpg",
  extract_pdf: "https://example.com/book35-extract.pdf",
  summary: "La décadence morale à travers le portrait vieillissant de Dorian Gray...",
},
{
  id: 36,
  title: "Le Meilleur des mondes",
  category_id: 2,
  author_id: 2,
  publisher_id: 2,
  comment_id: null,
  assessment_id: null,
  customer_id: 6,
  number_of_pages: 288,
  year_of_publication: 1932,
  average_ratings: null,
  cover_image: "https://example.com/book36-cover.jpg",
  extract_pdf: "https://example.com/book36-extract.pdf",
  summary: "Une société futuriste dystopique contrôlée par la génétique et la manipulation...",
},
{
  id: 37,
  title: "Moby Dick",
  category_id: 10,
  author_id: 10,
  publisher_id: 5,
  comment_id: null,
  assessment_id: null,
  customer_id: 7,
  number_of_pages: 635,
  year_of_publication: 1851,
  average_ratings: null,
  cover_image: "https://example.com/book37-cover.jpg",
  extract_pdf: "https://example.com/book37-extract.pdf",
  summary: "La chasse obsessionnelle à la baleine blanche par le capitaine Achab...",
},
{
  id: 38,
  title: "Les Trois Mousquetaires",
  category_id: 10,
  author_id: 10,
  publisher_id: 5,
  comment_id: null,
  assessment_id: null,
  customer_id: 8,
  number_of_pages: 704,
  year_of_publication: 1844,
  average_ratings: null,
  cover_image: "https://example.com/book38-cover.jpg",
  extract_pdf: "https://example.com/book38-extract.pdf",
  summary: "Les aventures palpitantes des mousquetaires d'Alexandre Dumas...",
},
{
  id: 39,
  title: "Don Quichotte",
  category_id: 6,
  author_id: 6,
  publisher_id: 1,
  comment_id: null,
  assessment_id: null,
  customer_id: 9,
  number_of_pages: 1072,
  year_of_publication: 1605,
  average_ratings: null,
  cover_image: "https://example.com/book39-cover.jpg",
  extract_pdf: "https://example.com/book39-extract.pdf",
  summary: "Les aventures comiques et tragi-comiques du chevalier Don Quichotte...",
},
{
  id: 40,
  title: "Le Hobbit",
  category_id: 1,
  author_id: 1,
  publisher_id: 1,
  comment_id: null,
  assessment_id: null,
  customer_id: 10,
  number_of_pages: 310,
  year_of_publication: 1937,
  average_ratings: null,
  cover_image: "https://example.com/book40-cover.jpg",
  extract_pdf: "https://example.com/book40-extract.pdf",
  summary: "Le voyage de Bilbo Baggins vers l'Erebor à la recherche du trésor gardé par Smaug...",
},
{
  id: 41,
  title: "Le Comte de Monte-Cristo",
  category_id: 6,
  author_id: 6,
  publisher_id: 3,
  comment_id: null,
  assessment_id: null,
  customer_id: 1,
  number_of_pages: 1200,
  year_of_publication: 1844,
  average_ratings: null,
  cover_image: "https://example.com/book41-cover.jpg",
  extract_pdf: "https://example.com/book41-extract.pdf",
  summary: "Edmond Dantès se venge de ceux qui l'ont trahi dans cette épopée de vengeance...",
},
{
  id: 42,
  title: "L'Odyssée",
  category_id: 10,
  author_id: 10,
  publisher_id: 5,
  comment_id: null,
  assessment_id: null,
  customer_id: 2,
  number_of_pages: 384,
  year_of_publication: 1985,
  average_ratings: null,
  cover_image: "https://example.com/book42-cover.jpg",
  extract_pdf: "https://example.com/book42-extract.pdf",
  summary: "Le périple d'Ulysse pour retourner à Ithaque après la guerre de Troie...",
},
{
  id: 43,
  title: "Le Rouge et le Noir",
  category_id: 4,
  author_id: 4,
  publisher_id: 3,
  comment_id: null,
  assessment_id: null,
  customer_id: 3,
  number_of_pages: 608,
  year_of_publication: 1830,
  average_ratings: null,
  cover_image: "https://example.com/book43-cover.jpg",
  extract_pdf: "https://example.com/book43-extract.pdf",
  summary: "Les ambitions et les passions de Julien Sorel dans la France du 19e siècle...",
},
{
  id: 44,
  title: "Les Misérables",
  category_id: 6,
  author_id: 6,
  publisher_id: 3,
  comment_id: null,
  assessment_id: null,
  customer_id: 4,
  number_of_pages: 1463,
  year_of_publication: 1862,
  average_ratings: null,
  cover_image: "https://example.com/book44-cover.jpg",
  extract_pdf: "https://example.com/book44-extract.pdf",
  summary: "Les vies entrelacées de plusieurs personnages au cours des décennies...",
},
{
  id: 45,
  title: "Orgueil et Préjugés",
  category_id: 4,
  author_id: 4,
  publisher_id: 3,
  comment_id: null,
  assessment_id: null,
  customer_id: 5,
  number_of_pages: 432,
  year_of_publication: 1813,
  average_ratings: null,
  cover_image: "https://example.com/book45-cover.jpg",
  extract_pdf: "https://example.com/book45-extract.pdf",
  summary: "L'amour et la classe sociale dans l'Angleterre du début du XIXe siècle...",
},
{
  id: 46,
  title: "Frankenstein",
  category_id: 9,
  author_id: 9,
  publisher_id: 1,
  comment_id: null,
  assessment_id: null,
  customer_id: 6,
  number_of_pages: 280,
  year_of_publication: 1818,
  average_ratings: null,
  cover_image: "https://example.com/book46-cover.jpg",
  extract_pdf: "https://example.com/book46-extract.pdf",
  summary: "Le roman gothique explorant les conséquences morales de la création...",
},
{
  id: 47,
  title: "Les Hauts de Hurlevent",
  category_id: 4,
  author_id: 4,
  publisher_id: 3,
  comment_id: null,
  assessment_id: null,
  customer_id: 7,
  number_of_pages: 342,
  year_of_publication: 1847,
  average_ratings: null,
  cover_image: "https://example.com/book47-cover.jpg",
  extract_pdf: "https://example.com/book47-extract.pdf",
  summary: "Les amours tragiques et la vengeance dans la lande anglaise...",
},
{
  id: 48,
  title: "Guerre et Paix",
  category_id: 6,
  author_id: 6,
  publisher_id: 3,
  comment_id: null,
  assessment_id: null,
  customer_id: 8,
  number_of_pages: 1440,
  year_of_publication: 1869,
  average_ratings: null,
  cover_image: "https://example.com/book48-cover.jpg",
  extract_pdf: "https://example.com/book48-extract.pdf",
  summary: "Les destins entrelacés de plusieurs familles russes pendant les guerres napoléoniennes...",
},
{
  id: 49,
  title: "Le Seigneur des Anneaux",
  category_id: 1,
  author_id: 1,
  publisher_id: 1,
  comment_id: null,
  assessment_id: null,
  customer_id: 9,
  number_of_pages: 1216,
  year_of_publication: 1954,
  average_ratings: null,
  cover_image: "https://example.com/book49-cover.jpg",
  extract_pdf: "https://example.com/book49-extract.pdf",
  summary: "L'épopée fantastique de Frodo pour détruire l'Anneau unique...",
},
{
  id: 50,
  title: "Les Frères Karamazov",
  category_id: 5,
  author_id: 5,
  publisher_id: 5,
  comment_id: null,
  assessment_id: null,
  customer_id: 10,
  number_of_pages: 824,
  year_of_publication: 1880,
  average_ratings: null,
  cover_image: "https://example.com/book50-cover.jpg",
  extract_pdf: "https://example.com/book50-extract.pdf",
  summary: "L'étude psychologique des relations entre le père Fiodor Pavlovitch et ses fils...",
},
];

export { books };
